-- Forma · Supabase setup
-- Incolla questo nello SQL Editor del tuo progetto Supabase e clicca RUN

CREATE TABLE IF NOT EXISTS public.tools (
  id           integer PRIMARY KEY,
  slug         text UNIQUE NOT NULL,
  name         text NOT NULL,
  category     text,
  pricing      text,
  featured     boolean DEFAULT false,
  website      text,
  added_at     date,
  votes        integer DEFAULT 0,
  tagline      text,
  description  text,
  tier         text,
  logo         text,
  editorial    text,
  use_cases    text[],
  pros         text[],
  cons         text[],
  tags         text[],
  i18n         jsonb DEFAULT '{}',
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read access" ON public.tools;
CREATE POLICY "Public read access" ON public.tools
  FOR SELECT TO anon USING (true);

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (1,'claude','Claude','Writing','Freemium',true,'https://claude.ai','2025-05-01','The AI assistant that reasons with nuance and care.','Claude is Anthropic''s flagship AI assistant designed for thoughtful conversation, complex reasoning, and long-form writing. Built with a focus on safety and helpfulness, it excels at nuanced tasks like analysis, research synthesis, editing, and code generation. Claude''s extended context window allows working with entire documents.','l','✦','The most thoughtful AI assistant available. Excels at nuanced reasoning and long-form tasks that other models fumble.',ARRAY['Long-form writing','Document analysis','Research synthesis','Code review','Brainstorming'],ARRAY['Exceptional reasoning depth','Handles large documents','Nuanced tone','Strong instruction following'],ARRAY['No image generation','Slower than some','Free tier has daily limits'],ARRAY['AI chat','writing','reasoning','analysis'],'{"es":{"tagline":"El asistente de IA que razona con matices.","description":"Claude es el asistente insignia de Anthropic, diseñado para conversaciones reflexivas y escritura de largo alcance. Destaca en análisis, síntesis de investigación, edición y generación de código.","useCases":["Escritura larga","Análisis de documentos","Síntesis de investigación","Revisión de código","Lluvia de ideas"],"pros":["Razonamiento profundo","Maneja documentos extensos","Tono matizado","Sigue instrucciones bien"],"cons":["Sin generación de imágenes","Más lento que otros","Límites en plan gratuito"],"editorial":"El asistente de IA más reflexivo. Ideal para razonamiento complejo y tareas largas."},"it":{"tagline":"L''assistente AI che ragiona con sfumatura.","description":"Claude è l''assistente AI di punta di Anthropic, progettato per conversazioni approfondite e scrittura lunga. Eccelle in analisi, sintesi di ricerca, editing e generazione di codice.","useCases":["Scrittura lunga","Analisi documenti","Sintesi della ricerca","Revisione codice","Brainstorming"],"pros":["Ragionamento profondo","Gestisce documenti estesi","Tono sfumato","Segue istruzioni bene"],"cons":["Nessuna generazione immagini","Più lento di altri","Limiti nel piano gratuito"],"editorial":"L''assistente AI più riflessivo. Ideale per ragionamento complesso e attività lunghe."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (2,'midjourney','Midjourney','Design','Paid',true,'https://midjourney.com','2025-04-28','Turn imagination into stunning visuals with AI.','Midjourney is the gold standard for AI image generation. The v6 model handles complex compositions and realistic lighting better than any competitor. Used by designers, artists, and marketers worldwide.','l','◈','Sets the aesthetic standard for AI image generation. If quality matters more than cost, this is still the benchmark.',ARRAY['Brand visuals','Concept art','Marketing imagery','Product mockups','Social media'],ARRAY['Best aesthetic quality','Consistent style control','Thriving community','Rapid iteration'],ARRAY['Requires Discord','No free tier','Text in images imperfect'],ARRAY['image generation','design','art','creative'],'{"es":{"tagline":"Convierte la imaginación en imágenes impresionantes.","description":"Midjourney es el estándar de oro en generación de imágenes con IA. El modelo v6 maneja composiciones complejas mejor que cualquier competidor.","useCases":["Visuales de marca","Arte conceptual","Imágenes de marketing","Maquetas de productos","Redes sociales"],"pros":["Mejor calidad estética","Control de estilo consistente","Comunidad activa","Iteración rápida"],"cons":["Requiere Discord","Sin plan gratuito","Texto en imágenes imperfecto"],"editorial":"El estándar estético en generación de imágenes con IA. Si la calidad importa más que el coste, sigue siendo el referente."},"it":{"tagline":"Trasforma l''immaginazione in visual straordinari.","description":"Midjourney è il punto di riferimento per la generazione di immagini con IA. Il modello v6 gestisce composizioni complesse meglio di qualsiasi concorrente.","useCases":["Visual per il brand","Arte concettuale","Immagini marketing","Mockup prodotti","Social media"],"pros":["Miglior qualità estetica","Controllo stile coerente","Comunità attiva","Iterazione rapida"],"cons":["Richiede Discord","Nessun piano gratuito","Testo nelle immagini imperfetto"],"editorial":"Lo standard estetico nella generazione di immagini con IA. Se la qualità conta più del costo, è ancora il punto di riferimento."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (3,'cursor','Cursor','Coding','Freemium',true,'https://cursor.sh','2025-04-20','The AI-first code editor that rewrites how you build.','Cursor is a VS Code fork rebuilt around AI-first workflows. Deep codebase understanding lets you chat with your code, generate features, fix bugs in context, and refactor with natural language.','l','⌘','The first editor that genuinely feels like pair programming. Cursor has changed the way serious developers work.',ARRAY['Feature generation','Bug fixing','Codebase navigation','Refactoring','Code explanation'],ARRAY['Deep codebase understanding','Excellent autocomplete','VS Code compatible','Active development'],ARRAY['Subscription can be expensive','AI calls have limits','Hallucinations in large codebases'],ARRAY['coding','IDE','developer tools','pair programming'],'{"es":{"tagline":"El editor de código con IA que cambia cómo construyes.","description":"Cursor es un fork de VS Code reconstruido en torno a flujos de trabajo con IA. Comprende tu código en profundidad para generar funciones, corregir errores y refactorizar.","useCases":["Generación de funciones","Corrección de errores","Navegación de código","Refactorización","Explicación de código"],"pros":["Comprensión profunda del código","Autocompletado excelente","Compatible con VS Code","Desarrollo activo"],"cons":["Suscripción puede ser cara","Llamadas de IA limitadas","Alucinaciones en bases grandes"],"editorial":"El primer editor que se siente como programación en pareja. Ha cambiado la forma de trabajar de los desarrolladores."},"it":{"tagline":"L''editor di codice AI-first che riscrive come si sviluppa.","description":"Cursor è un fork di VS Code ricostruito attorno a flussi di lavoro AI-first. Comprende il codice in profondità per generare funzionalità, correggere bug e fare refactoring.","useCases":["Generazione funzionalità","Correzione bug","Navigazione codebase","Refactoring","Spiegazione codice"],"pros":["Comprensione profonda del codice","Autocompletamento eccellente","Compatibile con VS Code","Sviluppo attivo"],"cons":["Abbonamento può essere costoso","Chiamate AI limitate","Allucinazioni su basi grandi"],"editorial":"Il primo editor che si sente davvero come programmazione in coppia. Ha cambiato il modo di lavorare degli sviluppatori."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (4,'perplexity','Perplexity','Research','Freemium',false,'https://perplexity.ai','2025-04-18','Answer engine for real-time, cited research.','Perplexity reimagines search as an AI conversation that cites every claim in real time. Pro users access multiple models and can upload PDFs for analysis.','m','◎','Search reimagined as a conversation with citations. The go-to for quick research with verifiable sources.',ARRAY['Market research','Fact checking','Academic research','Competitive analysis','News synthesis'],ARRAY['Real-time web access','Cites sources','Multi-model support','Clean UI'],ARRAY['Pro is pricey','Can oversimplify topics','Not ideal for creative tasks'],ARRAY['research','search','citations','real-time'],'{"es":{"tagline":"Motor de respuestas para investigación en tiempo real.","description":"Perplexity reimagina la búsqueda como una conversación con IA que cita cada afirmación. Los usuarios Pro acceden a múltiples modelos y pueden subir PDFs.","useCases":["Investigación de mercado","Verificación de hechos","Investigación académica","Análisis competitivo","Síntesis de noticias"],"pros":["Acceso web en tiempo real","Cita fuentes","Soporte multi-modelo","UI limpia"],"cons":["Pro es caro","Puede simplificar temas","No ideal para tareas creativas"],"editorial":"La búsqueda reimaginada como conversación con citas. El referente para investigación rápida y verificable."},"it":{"tagline":"Motore di risposte per ricerca in tempo reale.","description":"Perplexity reimmagina la ricerca come una conversazione AI che cita ogni affermazione. Gli utenti Pro accedono a più modelli e possono caricare PDF.","useCases":["Ricerca di mercato","Verifica dei fatti","Ricerca accademica","Analisi competitiva","Sintesi notizie"],"pros":["Accesso web in tempo reale","Cita le fonti","Supporto multi-modello","UI pulita"],"cons":["Pro è costoso","Può semplificare argomenti","Non ideale per creatività"],"editorial":"La ricerca reimmaginata come conversazione con citazioni. Il punto di riferimento per ricerche rapide e verificabili."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (5,'notion-ai','Notion AI','Productivity','Freemium',false,'https://notion.ai','2025-04-15','Think, write, and organize — with AI built in.','Notion AI is embedded directly in your workspace. Autofill populates database fields based on page content, and the AI writer keeps your company''s voice consistent.','m','□','The most contextually aware writing assistant — because it lives inside your actual knowledge base.',ARRAY['Document drafting','Meeting summaries','Project planning','Knowledge management','Templates'],ARRAY['Deeply integrated with Notion','Understands document context','Simple UX','Great for teams'],ARRAY['Tied to Notion ecosystem','Limited to in-app use','Occasional generic outputs'],ARRAY['productivity','writing','notes','workspace'],'{"es":{"tagline":"Piensa, escribe y organiza con IA integrada.","description":"Notion AI está integrado directamente en tu espacio de trabajo. El escritor con IA mantiene la voz de tu empresa consistente en toda la documentación.","useCases":["Redacción de documentos","Resúmenes de reuniones","Planificación de proyectos","Gestión del conocimiento","Plantillas"],"pros":["Integrado con Notion","Entiende el contexto","UX simple","Ideal para equipos"],"cons":["Vinculado al ecosistema Notion","Solo en la app","Resultados genéricos a veces"],"editorial":"El asistente de escritura más consciente del contexto, porque vive dentro de tu base de conocimiento real."},"it":{"tagline":"Pensa, scrivi e organizza con l''AI integrata.","description":"Notion AI è integrato direttamente nel tuo spazio di lavoro. Lo scrittore AI mantiene la voce della tua azienda coerente in tutta la documentazione.","useCases":["Redazione documenti","Riepiloghi riunioni","Pianificazione progetti","Gestione della conoscenza","Template"],"pros":["Integrato con Notion","Comprende il contesto","UX semplice","Ottimo per i team"],"cons":["Legato all''ecosistema Notion","Solo nell''app","Output generici a volte"],"editorial":"L''assistente di scrittura più consapevole del contesto, perché vive dentro la tua base di conoscenza reale."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (6,'runway-ml','Runway ML','Video','Freemium',false,'https://runwayml.com','2025-04-10','Professional video generation and editing for creators.','Runway is the leading AI video creation platform, used in professional film and advertising production. Gen-3 Alpha produces cinematic-quality video from text and images.','m','▷','Used in real Hollywood productions. If you need AI video that doesn''t look like AI video, start here.',ARRAY['Video generation','Background removal','Motion tracking','VFX','Social content'],ARRAY['Industry-grade quality','Comprehensive toolset','Professional integrations','Active updates'],ARRAY['Credits deplete fast','Steep learning curve','Expensive at scale'],ARRAY['video','generation','VFX','creative'],'{"es":{"tagline":"Generación y edición de vídeo profesional con IA.","description":"Runway es la plataforma líder en creación de vídeo con IA, usada en producción cinematográfica profesional. Gen-3 Alpha produce vídeo de calidad cinematográfica.","useCases":["Generación de vídeo","Eliminación de fondo","Seguimiento de movimiento","Efectos visuales","Contenido para redes"],"pros":["Calidad profesional","Herramientas completas","Integraciones profesionales","Actualizaciones frecuentes"],"cons":["Los créditos se agotan rápido","Curva de aprendizaje alta","Caro a gran escala"],"editorial":"Usado en producciones de Hollywood. Si necesitas vídeo con IA que no parezca IA, empieza aquí."},"it":{"tagline":"Generazione e editing video professionale con AI.","description":"Runway è la piattaforma leader nella creazione video con AI, usata nella produzione cinematografica professionale. Gen-3 Alpha produce video di qualità cinematografica.","useCases":["Generazione video","Rimozione sfondo","Motion tracking","Effetti visivi","Contenuto social"],"pros":["Qualità professionale","Toolkit completo","Integrazioni professionali","Aggiornamenti frequenti"],"cons":["I crediti si esauriscono in fretta","Curva di apprendimento alta","Costoso su larga scala"],"editorial":"Usato in produzioni Hollywood reali. Se hai bisogno di video AI che non sembri AI, inizia qui."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (7,'zapier-ai','Zapier AI','Automation','Freemium',false,'https://zapier.com','2025-04-08','Automate any workflow with natural language.','Zapier''s AI layer translates your intent into multi-step automations connecting 6,000+ apps. Combined with AI actions, it''s a powerful orchestration layer for any business workflow.','s','⚡','The automation backbone for thousands of businesses — now with AI that builds the workflows for you.',ARRAY['Workflow automation','App integration','Data routing','Lead management','Email automation'],ARRAY['6000+ integrations','No-code friendly','AI builds Zaps','Reliable infrastructure'],ARRAY['Cost scales with tasks','Complex Zaps can be brittle','AI suggestions not always accurate'],ARRAY['automation','no-code','integration','workflow'],'{"es":{"tagline":"Automatiza cualquier flujo con lenguaje natural.","description":"La capa de IA de Zapier traduce tu intención en automatizaciones de varios pasos que conectan 6.000+ apps. Es la capa de orquestación ideal para cualquier negocio.","useCases":["Automatización de flujos","Integración de apps","Enrutamiento de datos","Gestión de leads","Automatización de email"],"pros":["6000+ integraciones","Sin código","IA construye Zaps","Infraestructura fiable"],"cons":["Coste escala con tareas","Zaps complejos pueden fallar","Sugerencias de IA no siempre precisas"],"editorial":"La columna vertebral de automatización para miles de empresas, ahora con IA que construye los flujos por ti."},"it":{"tagline":"Automatizza qualsiasi flusso con linguaggio naturale.","description":"Lo strato AI di Zapier traduce la tua intenzione in automazioni multi-step che collegano 6.000+ app. È lo strato di orchestrazione ideale per qualsiasi flusso di lavoro.","useCases":["Automazione flussi","Integrazione app","Instradamento dati","Gestione lead","Automazione email"],"pros":["6000+ integrazioni","No-code friendly","L''AI costruisce i Zap","Infrastruttura affidabile"],"cons":["Il costo scala con i task","Zap complessi possono rompersi","Suggerimenti AI non sempre precisi"],"editorial":"La spina dorsale di automazione per migliaia di aziende, ora con AI che costruisce i flussi per te."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (8,'copy-ai','Copy.ai','Marketing','Freemium',false,'https://copy.ai','2025-04-05','Marketing copy at scale, without the blank page.','Copy.ai is built for marketing teams needing high-volume brand-consistent content. GTM AI workflows orchestrate multi-step content pipelines.','s','✎','Best for teams needing volume. Reliable for high-output marketing content at scale.',ARRAY['Ad copy','Email campaigns','Social media','Landing pages','Product descriptions'],ARRAY['Marketing-specific workflows','Brand voice consistency','Scalable production','Team collaboration'],ARRAY['Can feel formulaic','Best for short-form','Requires good briefs'],ARRAY['marketing','copywriting','content','GTM'],'{"es":{"tagline":"Textos de marketing a escala, sin la página en blanco.","description":"Copy.ai está diseñado para equipos de marketing que necesitan contenido de alto volumen consistente con la marca.","useCases":["Textos publicitarios","Campañas de email","Redes sociales","Landing pages","Descripciones de producto"],"pros":["Flujos específicos de marketing","Consistencia de voz de marca","Producción escalable","Colaboración en equipo"],"cons":["Puede sentirse formulaico","Mejor para textos cortos","Requiere buenos briefings"],"editorial":"Ideal para equipos que necesitan volumen. Fiable para contenido de marketing de alta producción."},"it":{"tagline":"Testi marketing su larga scala, senza il blocco della pagina bianca.","description":"Copy.ai è progettato per team marketing che necessitano di contenuti ad alto volume e coerenti con il brand.","useCases":["Testi pubblicitari","Campagne email","Social media","Landing page","Descrizioni prodotto"],"pros":["Flussi specifici per il marketing","Coerenza della voce del brand","Produzione scalabile","Collaborazione in team"],"cons":["Può sembrare formulaico","Meglio per testi brevi","Richiede brief dettagliati"],"editorial":"Ideale per team che necessitano di volume. Affidabile per contenuti marketing ad alta produzione."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (9,'github-copilot','GitHub Copilot','Coding','Paid',false,'https://github.com/features/copilot','2025-04-02','Your AI pair programmer, right in your editor.','GitHub Copilot integrates AI assistance directly into VS Code, JetBrains, and more. Copilot Chat allows natural language conversations about your code.','m','◉','The default choice for developers in the GitHub ecosystem. Mature, reliable, and getting better fast.',ARRAY['Code completion','Test generation','Documentation','Bug detection','Code explanation'],ARRAY['Seamless editor integration','Multi-language support','GitHub ecosystem','Fast completions'],ARRAY['Monthly subscription','Occasional insecure suggestions','Requires internet'],ARRAY['coding','IDE','GitHub','autocomplete'],'{"es":{"tagline":"Tu programador en pareja con IA, en tu editor.","description":"GitHub Copilot integra asistencia de IA directamente en VS Code, JetBrains y más. Copilot Chat permite conversaciones en lenguaje natural sobre tu código.","useCases":["Completado de código","Generación de tests","Documentación","Detección de errores","Explicación de código"],"pros":["Integración perfecta en el editor","Soporte multi-lenguaje","Ecosistema GitHub","Completados rápidos"],"cons":["Suscripción mensual","Sugerencias inseguras ocasionales","Requiere internet"],"editorial":"La elección por defecto para desarrolladores en el ecosistema GitHub. Maduro, fiable y mejorando rápido."},"it":{"tagline":"Il tuo programmatore in coppia con AI, nel tuo editor.","description":"GitHub Copilot integra l''assistenza AI direttamente in VS Code, JetBrains e altri. Copilot Chat permette conversazioni in linguaggio naturale sul tuo codice.","useCases":["Completamento codice","Generazione test","Documentazione","Rilevamento bug","Spiegazione codice"],"pros":["Integrazione perfetta nell''editor","Supporto multi-linguaggio","Ecosistema GitHub","Completamenti veloci"],"cons":["Abbonamento mensile","Suggerimenti non sicuri occasionali","Richiede internet"],"editorial":"La scelta predefinita per i developer nell''ecosistema GitHub. Maturo, affidabile e in costante miglioramento."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (10,'jasper','Jasper','Marketing','Paid',false,'https://jasper.ai','2025-03-28','Enterprise content at the speed of thought.','Jasper is the enterprise AI writing platform trusted by major brands. Features Brand Voice, pre-built marketing templates, Campaign builder, and SurferSEO integration.','s','J','Enterprise-grade brand control is Jasper''s edge. Overkill for solo creators, powerful for large teams.',ARRAY['Blog content','SEO writing','Social campaigns','Email sequences','Brand content'],ARRAY['Enterprise brand control','SEO integration','Template library','Team permissions'],ARRAY['Expensive for small teams','Can produce generic content','Needs heavy prompting'],ARRAY['marketing','content','enterprise','SEO'],'{"es":{"tagline":"Contenido empresarial a la velocidad del pensamiento.","description":"Jasper es la plataforma de escritura con IA para empresas. Incluye Brand Voice, plantillas de marketing y integración con SurferSEO.","useCases":["Contenido de blog","Escritura SEO","Campañas sociales","Secuencias de email","Contenido de marca"],"pros":["Control de marca empresarial","Integración SEO","Biblioteca de plantillas","Permisos de equipo"],"cons":["Caro para equipos pequeños","Puede generar contenido genérico","Requiere prompts detallados"],"editorial":"El control de marca empresarial es la ventaja de Jasper. Excesivo para creadores individuales, poderoso para grandes equipos."},"it":{"tagline":"Contenuti aziendali alla velocità del pensiero.","description":"Jasper è la piattaforma di scrittura AI per le aziende. Include Brand Voice, template di marketing e integrazione con SurferSEO.","useCases":["Contenuto blog","Scrittura SEO","Campagne social","Sequenze email","Contenuto brand"],"pros":["Controllo brand aziendale","Integrazione SEO","Libreria template","Permessi team"],"cons":["Costoso per team piccoli","Può generare contenuti generici","Richiede prompt dettagliati"],"editorial":"Il controllo del brand aziendale è il punto di forza di Jasper. Eccessivo per creator individuali, potente per grandi team."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (11,'otter-ai','Otter.ai','Productivity','Freemium',false,'https://otter.ai','2025-03-25','AI meeting notes and transcription in real time.','Otter.ai joins your meetings transcribing in real time with speaker identification. Integrates natively with Zoom, Google Meet, and Teams.','s','◑','The most painless way to never miss a meeting detail. Speaker identification alone saves hours of re-listening.',ARRAY['Meeting transcription','Note taking','Action items','Interview recording','Sales call analysis'],ARRAY['Real-time transcription','Speaker identification','Native integrations','Searchable archive'],ARRAY['Accuracy drops with accents','Free tier limited','Privacy considerations'],ARRAY['meetings','transcription','productivity','notes'],'{"es":{"tagline":"Notas de reuniones y transcripción con IA en tiempo real.","description":"Otter.ai se une a tus reuniones transcribiendo en tiempo real con identificación de interlocutores. Se integra con Zoom, Google Meet y Teams.","useCases":["Transcripción de reuniones","Toma de notas","Puntos de acción","Grabación de entrevistas","Análisis de llamadas de ventas"],"pros":["Transcripción en tiempo real","Identificación de interlocutores","Integraciones nativas","Archivo buscable"],"cons":["Precisión baja con acentos","Plan gratuito limitado","Consideraciones de privacidad"],"editorial":"La forma más sencilla de no perder nunca un detalle de una reunión."},"it":{"tagline":"Note di riunioni e trascrizione AI in tempo reale.","description":"Otter.ai si unisce alle tue riunioni trascrivendo in tempo reale con identificazione dei partecipanti. Si integra con Zoom, Google Meet e Teams.","useCases":["Trascrizione riunioni","Presa di note","Punti d''azione","Registrazione interviste","Analisi chiamate vendita"],"pros":["Trascrizione in tempo reale","Identificazione dei partecipanti","Integrazioni native","Archivio ricercabile"],"cons":["Precisione ridotta con accenti","Piano gratuito limitato","Considerazioni sulla privacy"],"editorial":"Il modo più semplice per non perdere mai un dettaglio di una riunione."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (12,'elevenlabs','ElevenLabs','Video','Freemium',false,'https://elevenlabs.io','2025-03-20','Ultra-realistic AI voice generation and cloning.','ElevenLabs produces the most natural-sounding AI voices with fine-grained control over emotion, pacing, and style. Voice cloning creates a replica from just a few minutes of audio.','m','♪','Nothing comes close for voice quality. The emotion controls change what''s possible in audio production.',ARRAY['Voiceovers','Audiobooks','Podcast production','Video dubbing','Accessibility'],ARRAY['Best voice quality','Emotion and style control','Voice cloning','Multi-language'],ARRAY['Cost scales with characters','Ethical concerns with cloning','Rate limits on free'],ARRAY['voice','audio','TTS','cloning'],'{"es":{"tagline":"Generación y clonación de voz con IA ultra-realista.","description":"ElevenLabs produce las voces con IA más naturales con control preciso de emoción, ritmo y estilo. La clonación de voz crea una réplica con solo minutos de audio.","useCases":["Voces en off","Audiolibros","Producción de podcasts","Doblaje de vídeo","Accesibilidad"],"pros":["Mejor calidad de voz","Control de emoción y estilo","Clonación de voz","Multi-idioma"],"cons":["Coste escala con caracteres","Preocupaciones éticas","Límites en plan gratuito"],"editorial":"Nada se acerca a esta calidad de voz. Los controles de emoción cambian lo que es posible en producción de audio."},"it":{"tagline":"Generazione e clonazione vocale AI ultra-realistica.","description":"ElevenLabs produce le voci AI più naturali con controllo preciso su emozione, ritmo e stile. La clonazione vocale crea una replica con pochi minuti di audio.","useCases":["Voci fuori campo","Audiolibri","Produzione podcast","Doppiaggio video","Accessibilità"],"pros":["Migliore qualità vocale","Controllo emozione e stile","Clonazione vocale","Multi-lingua"],"cons":["Il costo scala con i caratteri","Preoccupazioni etiche","Limiti nel piano gratuito"],"editorial":"Niente si avvicina a questa qualità vocale. I controlli dell''emozione cambiano ciò che è possibile nella produzione audio."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (13,'descript','Descript','Video','Freemium',false,'https://descript.com','2025-03-15','Edit video and audio like a document.','Descript makes video and podcast editing as intuitive as editing a Word doc. Delete a word in the transcript and it removes it from the video.','s','◈','The editing paradigm shift for podcasters. Once you edit by transcript, you can''t go back.',ARRAY['Podcast editing','Video production','Screen recording','Social clips','Transcription'],ARRAY['Intuitive editing interface','Great overdub feature','Studio Sound is excellent','Strong clip creation'],ARRAY['AI voice cloning limits','Export can be slow','Complex projects lag'],ARRAY['video','podcast','editing','transcription'],'{"es":{"tagline":"Edita vídeo y audio como un documento.","description":"Descript hace que la edición de vídeo y podcast sea tan intuitiva como editar un documento Word. Elimina una palabra en la transcripción y la quita del vídeo.","useCases":["Edición de podcasts","Producción de vídeo","Grabación de pantalla","Clips para redes","Transcripción"],"pros":["Interfaz de edición intuitiva","Función overdub excelente","Studio Sound es increíble","Creación de clips sólida"],"cons":["Límites en clonación de voz","Exportación puede ser lenta","Proyectos complejos lentos"],"editorial":"El cambio de paradigma para podcasters. Una vez que editas por transcripción, no puedes volver atrás."},"it":{"tagline":"Modifica video e audio come un documento.","description":"Descript rende l''editing video e podcast intuitivo come modificare un documento Word. Elimina una parola dalla trascrizione e la rimuove dal video.","useCases":["Editing podcast","Produzione video","Registrazione schermo","Clip per social","Trascrizione"],"pros":["Interfaccia di editing intuitiva","Funzione overdub eccellente","Studio Sound è fantastico","Creazione clip solida"],"cons":["Limiti nella clonazione vocale","Export può essere lento","Progetti complessi lenti"],"editorial":"Il cambio di paradigma per i podcaster. Una volta che modifichi per trascrizione, non puoi tornare indietro."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (14,'grammarly','Grammarly','Writing','Freemium',false,'https://grammarly.com','2025-03-10','AI writing assistance for clarity and confidence.','Grammarly has evolved into a full AI writing assistant. The generative AI layer rewrites paragraphs, adjusts tone, and maintains brand consistency across browsers and Google Workspace.','s','G','The safety net every writer needs. Integration depth across every writing surface is unmatched.',ARRAY['Proofreading','Tone adjustment','Email writing','Document editing','Content rewriting'],ARRAY['Ubiquitous integration','Easy to use','Tone detection','Real-time suggestions'],ARRAY['Premium is pricey','Sometimes over-corrects','Less powerful for creative writing'],ARRAY['writing','grammar','proofreading','editing'],'{"es":{"tagline":"Asistencia de escritura con IA para claridad y confianza.","description":"Grammarly ha evolucionado hasta convertirse en un asistente de escritura con IA completo. Reescribe párrafos, ajusta el tono y mantiene la coherencia de marca.","useCases":["Corrección","Ajuste de tono","Redacción de emails","Edición de documentos","Reescritura de contenido"],"pros":["Integración ubicua","Fácil de usar","Detección de tono","Sugerencias en tiempo real"],"cons":["Premium es caro","A veces corrige en exceso","Menos potente para escritura creativa"],"editorial":"La red de seguridad que todo escritor necesita. Su profundidad de integración en todas las superficies de escritura no tiene rival."},"it":{"tagline":"Assistenza alla scrittura AI per chiarezza e fiducia.","description":"Grammarly si è evoluto in un assistente di scrittura AI completo. Riscrive paragrafi, regola il tono e mantiene la coerenza del brand.","useCases":["Correzione","Regolazione del tono","Scrittura email","Editing documenti","Riscrittura contenuti"],"pros":["Integrazione ovunque","Facile da usare","Rilevamento del tono","Suggerimenti in tempo reale"],"cons":["Premium è costoso","A volte corregge troppo","Meno potente per scrittura creativa"],"editorial":"La rete di sicurezza di cui ogni scrittore ha bisogno. La profondità di integrazione su ogni superficie di scrittura non ha rivali."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (15,'make','Make','Automation','Freemium',false,'https://make.com','2025-03-05','Visual automation for complex multi-step workflows.','Make (formerly Integromat) is the most powerful visual automation platform for non-developers. Canvas-based workflow builder handles complex logic and data transformation.','s','◎','The power user''s Zapier. If you need real conditional logic and data transformation, Make is where you graduate to.',ARRAY['Complex automation','Data transformation','API integration','Business logic','Error handling'],ARRAY['Visual workflow builder','Handles complex logic','More affordable than Zapier','Powerful data tools'],ARRAY['Steeper learning curve','Fewer native integrations','Support can be slow'],ARRAY['automation','no-code','integration','visual'],'{"es":{"tagline":"Automatización visual para flujos complejos.","description":"Make (antes Integromat) es la plataforma de automatización visual más potente. El constructor de flujos gestiona lógica compleja y transformación de datos.","useCases":["Automatización compleja","Transformación de datos","Integración API","Lógica de negocio","Manejo de errores"],"pros":["Constructor visual","Maneja lógica compleja","Más asequible que Zapier","Herramientas de datos potentes"],"cons":["Curva de aprendizaje alta","Menos integraciones nativas","Soporte puede ser lento"],"editorial":"El Zapier para usuarios avanzados. Si necesitas lógica condicional real y transformación de datos, aquí es donde llegas."},"it":{"tagline":"Automazione visuale per flussi complessi.","description":"Make (ex Integromat) è la piattaforma di automazione visuale più potente. Il builder di flussi gestisce logica complessa e trasformazione dati.","useCases":["Automazione complessa","Trasformazione dati","Integrazione API","Logica di business","Gestione errori"],"pros":["Builder visuale","Gestisce logica complessa","Più economico di Zapier","Strumenti dati potenti"],"cons":["Curva di apprendimento alta","Meno integrazioni native","Il supporto può essere lento"],"editorial":"Il Zapier per gli utenti avanzati. Se hai bisogno di logica condizionale reale e trasformazione dati, Make è dove arrivi."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (16,'canva-ai','Canva AI','Design','Freemium',false,'https://canva.com','2025-03-01','Design anything. Create everywhere. Powered by AI.','Canva''s Magic Suite brings AI to the world''s most popular design platform. Magic Design generates complete branded templates from a prompt. Used by 135+ million people monthly.','m','C','The most accessible design AI. Not the most powerful, but the combination of ease and breadth is hard to beat.',ARRAY['Social media design','Presentations','Marketing materials','Brand assets','Video editing'],ARRAY['Extremely easy to use','Huge template library','Brand kit integration','Collaboration features'],ARRAY['AI quality lags dedicated tools','Pro needed for best features','Less control than Figma'],ARRAY['design','templates','social media','branding'],'{"es":{"tagline":"Diseña cualquier cosa. Crea en todas partes.","description":"Magic Suite de Canva lleva la IA a la plataforma de diseño más popular del mundo. Magic Design genera plantillas completas de marca a partir de un prompt.","useCases":["Diseño para redes sociales","Presentaciones","Materiales de marketing","Activos de marca","Edición de vídeo"],"pros":["Extremadamente fácil de usar","Enorme biblioteca de plantillas","Integración de kit de marca","Funciones de colaboración"],"cons":["Calidad de IA inferior a herramientas dedicadas","Pro necesario para lo mejor","Menos control que Figma"],"editorial":"La IA de diseño más accesible. No la más potente, pero la combinación de facilidad y amplitud es difícil de superar."},"it":{"tagline":"Progetta tutto. Crea ovunque. Potenziato dall''AI.","description":"Magic Suite di Canva porta l''AI sulla piattaforma di design più popolare al mondo. Magic Design genera template completi di brand da un prompt.","useCases":["Design per social media","Presentazioni","Materiali marketing","Asset del brand","Editing video"],"pros":["Estremamente facile da usare","Enorme libreria di template","Integrazione kit brand","Funzionalità di collaborazione"],"cons":["Qualità AI inferiore a strumenti dedicati","Pro necessario per il meglio","Meno controllo di Figma"],"editorial":"L''AI di design più accessibile. Non la più potente, ma la combinazione di facilità e ampiezza è difficile da battere."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (17,'salesforce-einstein','Salesforce Einstein','Sales','Paid',false,'https://salesforce.com/products/einstein','2025-02-25','AI that turns your CRM data into revenue intelligence.','Salesforce Einstein embeds AI across the entire platform — predicting deal outcomes, scoring leads, writing follow-up emails, and forecasting revenue.','s','⚙','The most comprehensive AI in enterprise sales — if you''re already in the Salesforce ecosystem.',ARRAY['Lead scoring','Deal forecasting','Email generation','Call summaries','Pipeline analysis'],ARRAY['Deep CRM integration','Predictive analytics','Automated data entry','Enterprise scale'],ARRAY['Extremely expensive','Complex implementation','Requires Salesforce CRM'],ARRAY['sales','CRM','forecasting','enterprise'],'{"es":{"tagline":"IA que convierte tus datos de CRM en inteligencia de ventas.","description":"Salesforce Einstein incorpora IA en toda la plataforma: predice resultados, puntúa leads, escribe emails de seguimiento y pronostica ingresos.","useCases":["Puntuación de leads","Predicción de acuerdos","Generación de emails","Resúmenes de llamadas","Análisis de pipeline"],"pros":["Integración profunda con CRM","Análisis predictivo","Entrada de datos automatizada","Escala empresarial"],"cons":["Extremadamente caro","Implementación compleja","Requiere Salesforce CRM"],"editorial":"La IA más completa en ventas empresariales, si ya estás en el ecosistema Salesforce."},"it":{"tagline":"AI che trasforma i dati CRM in intelligenza revenue.","description":"Salesforce Einstein integra l''AI in tutta la piattaforma: prevede esiti, punteggia lead, scrive email di follow-up e prevede i ricavi.","useCases":["Scoring dei lead","Previsione trattative","Generazione email","Riepiloghi chiamate","Analisi pipeline"],"pros":["Integrazione profonda con CRM","Analytics predittiva","Inserimento dati automatizzato","Scala aziendale"],"cons":["Estremamente costoso","Implementazione complessa","Richiede Salesforce CRM"],"editorial":"L''AI più completa nelle vendite aziendali, se sei già nell''ecosistema Salesforce."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (18,'gong','Gong','Sales','Paid',false,'https://gong.io','2025-02-20','Revenue intelligence from every sales conversation.','Gong analyzes every sales call, email, and meeting with AI to surface what''s working. It identifies deal risks, coaching opportunities, and competitive insights automatically.','m','◉','The tool that makes revenue leaders sleep better. Gong''s call analysis has been worth the price for many teams.',ARRAY['Call analysis','Deal intelligence','Sales coaching','Forecast accuracy','Competitive insights'],ARRAY['Best-in-class call analysis','Actionable insights','Coaching features','Integrates everywhere'],ARRAY['Very expensive','Requires team adoption','Data security concerns'],ARRAY['sales','revenue intelligence','calls','coaching'],'{"es":{"tagline":"Inteligencia de ingresos en cada conversación de ventas.","description":"Gong analiza cada llamada, email y reunión de ventas con IA para identificar qué funciona. Detecta riesgos en acuerdos y oportunidades de coaching automáticamente.","useCases":["Análisis de llamadas","Inteligencia de acuerdos","Coaching de ventas","Precisión de previsiones","Insights competitivos"],"pros":["Análisis de llamadas líder","Insights accionables","Funciones de coaching","Se integra en todas partes"],"cons":["Muy caro","Requiere adopción del equipo","Preocupaciones de seguridad de datos"],"editorial":"La herramienta que permite dormir mejor a los líderes de ingresos. El análisis de llamadas de Gong ha valido la pena para muchos equipos."},"it":{"tagline":"Intelligenza revenue da ogni conversazione di vendita.","description":"Gong analizza ogni chiamata, email e riunione di vendita con AI per identificare cosa funziona. Rileva rischi nelle trattative e opportunità di coaching automaticamente.","useCases":["Analisi chiamate","Intelligenza trattative","Sales coaching","Accuratezza previsioni","Insight competitivi"],"pros":["Analisi chiamate leader","Insight azionabili","Funzionalità di coaching","Si integra ovunque"],"cons":["Molto costoso","Richiede adozione del team","Preoccupazioni sicurezza dati"],"editorial":"Lo strumento che fa dormire meglio i revenue leader. L''analisi delle chiamate di Gong ha valso il prezzo per molti team."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (19,'stable-diffusion','Stable Diffusion','Design','Free',false,'https://stability.ai','2025-02-15','Open-source image generation with infinite control.','Stable Diffusion powers thousands of AI image tools. Run it locally for free, train custom models, or use the API. With ComfyUI, professionals get pixel-perfect control.','s','◈','The power tool for anyone needing total control over image generation. Steep curve, but the ceiling is unlimited.',ARRAY['Custom model training','Brand-specific imagery','Local generation','Fine-tuning','Research'],ARRAY['Free and open-source','Maximum control','Run locally','Custom training'],ARRAY['Technical setup required','Hardware dependent','Requires prompt expertise'],ARRAY['image generation','open-source','design','local'],'{"es":{"tagline":"Generación de imágenes de código abierto con control infinito.","description":"Stable Diffusion impulsa miles de herramientas de imágenes con IA. Ejecútalo localmente de forma gratuita, entrena modelos personalizados o usa la API.","useCases":["Entrenamiento de modelos personalizados","Imágenes específicas de marca","Generación local","Fine-tuning","Investigación"],"pros":["Gratuito y de código abierto","Máximo control","Ejecutar localmente","Entrenamiento personalizado"],"cons":["Configuración técnica requerida","Dependiente del hardware","Requiere expertise en prompts"],"editorial":"La herramienta de poder para quien necesita control total. Curva empinada, pero sin techo."},"it":{"tagline":"Generazione immagini open-source con controllo infinito.","description":"Stable Diffusion alimenta migliaia di strumenti AI per immagini. Eseguilo localmente gratuitamente, allena modelli personalizzati o usa l''API.","useCases":["Training modelli personalizzati","Immagini specifiche del brand","Generazione locale","Fine-tuning","Ricerca"],"pros":["Gratuito e open-source","Massimo controllo","Esegui localmente","Training personalizzato"],"cons":["Configurazione tecnica richiesta","Dipendente dall''hardware","Richiede expertise nei prompt"],"editorial":"Lo strumento potente per chi ha bisogno di controllo totale. Curva ripida, ma senza limite."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (20,'gamma','Gamma','Productivity','Freemium',false,'https://gamma.app','2025-02-10','Beautiful presentations, built by AI in minutes.','Gamma generates complete, beautifully designed presentations from a prompt or outline in seconds. Creates web-first decks that are shareable via link.','m','γ','The fastest path from idea to polished deck. Output quality consistently surprises people seeing it for the first time.',ARRAY['Presentations','Pitch decks','Reports','Proposals','Training materials'],ARRAY['Beautiful output instantly','Web-first and shareable','No design skills needed','Fast iteration'],ARRAY['Limited customization','Brand control is limited','Offline not available'],ARRAY['presentations','design','productivity','decks'],'{"es":{"tagline":"Presentaciones hermosas creadas por IA en minutos.","description":"Gamma genera presentaciones completas y bellamente diseñadas a partir de un prompt en segundos. Crea presentaciones web-first compartibles por enlace.","useCases":["Presentaciones","Pitch decks","Informes","Propuestas","Materiales de formación"],"pros":["Resultado hermoso al instante","Web-first y compartible","No necesitas habilidades de diseño","Iteración rápida"],"cons":["Personalización limitada","Control de marca limitado","No disponible sin conexión"],"editorial":"El camino más rápido de la idea al deck pulido. La calidad del resultado sorprende constantemente a quienes lo ven por primera vez."},"it":{"tagline":"Presentazioni bellissime create dall''AI in minuti.","description":"Gamma genera presentazioni complete e ben progettate da un prompt in pochi secondi. Crea deck web-first condivisibili via link.","useCases":["Presentazioni","Pitch deck","Report","Proposte","Materiali formativi"],"pros":["Risultato bellissimo all''istante","Web-first e condivisibile","Nessuna competenza di design richiesta","Iterazione rapida"],"cons":["Personalizzazione limitata","Controllo brand limitato","Non disponibile offline"],"editorial":"Il percorso più veloce dall''idea al deck rifinito. La qualità del risultato sorprende costantemente chi lo vede per la prima volta."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (21,'consensus','Consensus','Research','Freemium',false,'https://consensus.app','2025-02-05','Search the scientific literature with AI clarity.','Consensus searches and synthesizes findings from 200 million scientific papers. Identifies the scientific consensus on any question with citations.','s','◎','The only AI that tells you what science actually says, with receipts. Essential for evidence-based decisions.',ARRAY['Literature review','Evidence synthesis','Health research','Scientific consensus','Fact-checking'],ARRAY['200M+ papers indexed','Consensus meter','Excellent citations','Simple interface'],ARRAY['Only scientific literature','Not for real-time news','Pro needed for bulk use'],ARRAY['research','science','academic','citations'],'{"es":{"tagline":"Busca en la literatura científica con claridad de IA.","description":"Consensus busca y sintetiza hallazgos de 200 millones de artículos científicos. Identifica el consenso científico sobre cualquier pregunta con citas.","useCases":["Revisión bibliográfica","Síntesis de evidencia","Investigación de salud","Consenso científico","Verificación de hechos"],"pros":["200M+ artículos indexados","Medidor de consenso","Excelentes citas","Interfaz simple"],"cons":["Solo literatura científica","No para noticias en tiempo real","Pro necesario para uso masivo"],"editorial":"La única IA que te dice qué dice realmente la ciencia, con fuentes. Esencial para decisiones basadas en evidencia."},"it":{"tagline":"Cerca nella letteratura scientifica con chiarezza AI.","description":"Consensus cerca e sintetizza risultati da 200 milioni di articoli scientifici. Identifica il consenso scientifico su qualsiasi domanda con citazioni.","useCases":["Revisione letteratura","Sintesi delle evidenze","Ricerca sanitaria","Consenso scientifico","Verifica dei fatti"],"pros":["200M+ articoli indicizzati","Metro del consenso","Ottime citazioni","Interfaccia semplice"],"cons":["Solo letteratura scientifica","Non per notizie in tempo reale","Pro necessario per uso intensivo"],"editorial":"L''unica AI che ti dice cosa dice davvero la scienza, con fonti. Essenziale per decisioni basate su evidenze."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (22,'clay','Clay','Sales','Paid',false,'https://clay.com','2025-02-01','AI-powered data enrichment for outbound sales.','Clay automates prospect research pulling from 75+ enrichment sources and combining with AI to write hyper-personalized outreach at scale.','m','◑','The tool that makes cold outreach feel warm. Clay is non-negotiable for high-performance outbound teams.',ARRAY['Lead enrichment','Personalized outreach','Prospect research','Email campaigns','Data operations'],ARRAY['75+ data sources','AI personalization at scale','Waterfall enrichment','CRM integrations'],ARRAY['Learning curve is steep','Expensive for large lists','Requires data literacy'],ARRAY['sales','enrichment','outbound','prospecting'],'{"es":{"tagline":"Enriquecimiento de datos con IA para ventas outbound.","description":"Clay automatiza la investigación de prospectos extrayendo de 75+ fuentes y combinando con IA para escribir outreach hiper-personalizado a escala.","useCases":["Enriquecimiento de leads","Outreach personalizado","Investigación de prospectos","Campañas de email","Operaciones de datos"],"pros":["75+ fuentes de datos","Personalización con IA a escala","Enriquecimiento en cascada","Integraciones CRM"],"cons":["Curva de aprendizaje alta","Caro para listas grandes","Requiere alfabetización de datos"],"editorial":"La herramienta que hace que el outreach frío se sienta cálido. Imprescindible para equipos outbound de alto rendimiento."},"it":{"tagline":"Arricchimento dati AI per le vendite outbound.","description":"Clay automatizza la ricerca dei prospect attingendo da 75+ fonti e combinando con AI per scrivere outreach iper-personalizzato su larga scala.","useCases":["Arricchimento lead","Outreach personalizzato","Ricerca prospect","Campagne email","Operazioni dati"],"pros":["75+ fonti dati","Personalizzazione AI su larga scala","Arricchimento a cascata","Integrazioni CRM"],"cons":["Curva di apprendimento alta","Costoso per liste grandi","Richiede competenze sui dati"],"editorial":"Lo strumento che rende il cold outreach caldo. Clay è irrinunciabile per i team outbound ad alte prestazioni."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (23,'fireflies-ai','Fireflies.ai','Productivity','Freemium',false,'https://fireflies.ai','2025-01-25','Your AI meeting assistant that never forgets.','Fireflies joins video calls automatically, records, transcribes, and creates searchable notes with AI summaries and action items.','s','✦','Set it and forget it meeting intelligence. CRM auto-logging saves sales reps hours of manual entry weekly.',ARRAY['Meeting recording','Action items','CRM logging','Sales call analysis','Team collaboration'],ARRAY['Auto-joins meetings','CRM integration','Searchable archive','Good free tier'],ARRAY['Transcription accuracy varies','Storage limits on free','Can feel intrusive'],ARRAY['meetings','productivity','transcription','CRM'],'{"es":{"tagline":"Tu asistente de reuniones con IA que nunca olvida.","description":"Fireflies se une automáticamente a las videollamadas, graba, transcribe y crea notas buscables con resúmenes de IA y puntos de acción.","useCases":["Grabación de reuniones","Puntos de acción","Registro en CRM","Análisis de llamadas de ventas","Colaboración en equipo"],"pros":["Se une automáticamente a reuniones","Integración CRM","Archivo buscable","Buen plan gratuito"],"cons":["Precisión de transcripción variable","Límites de almacenamiento en gratuito","Puede sentirse intrusivo"],"editorial":"Inteligencia de reuniones que se configura sola. El registro automático en CRM ahorra horas a los comerciales cada semana."},"it":{"tagline":"Il tuo assistente AI per le riunioni che non dimentica mai.","description":"Fireflies si unisce automaticamente alle videochiamate, registra, trascrive e crea note ricercabili con riepiloghi AI e punti d''azione.","useCases":["Registrazione riunioni","Punti d''azione","Registrazione CRM","Analisi chiamate vendita","Collaborazione team"],"pros":["Si unisce automaticamente alle riunioni","Integrazione CRM","Archivio ricercabile","Buon piano gratuito"],"cons":["Precisione trascrizione variabile","Limiti di storage nel gratuito","Può sembrare intrusivo"],"editorial":"Intelligenza delle riunioni plug-and-play. Il logging automatico nel CRM fa risparmiare ore ai sales rep ogni settimana."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (24,'writesonic','Writesonic','Writing','Freemium',false,'https://writesonic.com','2025-01-20','SEO-first AI writing for blogs and landing pages.','Writesonic combines AI writing with real-time SEO data. Article Writer 6.0 researches, outlines, and writes full blog posts with accurate citations.','s','✎','A solid workhorse for SEO content at scale. The real-time search integration keeps content accurate.',ARRAY['Blog writing','SEO content','Landing pages','Product descriptions','Social media'],ARRAY['SEO-optimized output','Real-time web search','Long-form generation','Affordable plans'],ARRAY['Quality inconsistent','Needs heavy editing','Less nuanced than Claude'],ARRAY['writing','SEO','content','marketing'],'{"es":{"tagline":"Escritura con IA orientada al SEO para blogs y landing pages.","description":"Writesonic combina escritura con IA con datos SEO en tiempo real. Article Writer 6.0 investiga, esboza y escribe posts completos con citas precisas.","useCases":["Escritura de blogs","Contenido SEO","Landing pages","Descripciones de producto","Redes sociales"],"pros":["Resultado optimizado para SEO","Búsqueda web en tiempo real","Generación de largo alcance","Planes asequibles"],"cons":["Calidad inconsistente","Necesita mucha edición","Menos matizado que Claude"],"editorial":"Un sólido trabajador para contenido SEO a escala. La integración de búsqueda en tiempo real mantiene el contenido preciso."},"it":{"tagline":"Scrittura AI SEO-first per blog e landing page.","description":"Writesonic combina la scrittura AI con dati SEO in tempo reale. Article Writer 6.0 ricerca, struttura e scrive post completi con citazioni accurate.","useCases":["Scrittura blog","Contenuto SEO","Landing page","Descrizioni prodotto","Social media"],"pros":["Output ottimizzato per SEO","Ricerca web in tempo reale","Generazione long-form","Piani accessibili"],"cons":["Qualità inconsistente","Richiede molta revisione","Meno sfumato di Claude"],"editorial":"Un solido workhorse per contenuti SEO su larga scala. L''integrazione della ricerca in tempo reale mantiene i contenuti accurati."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (25,'gemini','Gemini','Writing','Freemium',false,'https://gemini.google.com','2025-05-10','Google''s most capable multimodal AI assistant.','Gemini is Google flagship AI model deeply integrated with Google Workspace. Gemini 1.5 Pro handles 1M token context windows making it exceptional for large codebases.','m','✧','The context window king. When you need to analyze an entire codebase in one shot, Gemini has no rival.',ARRAY['Document analysis','Code generation','Image understanding','Long context tasks','Google Workspace'],ARRAY['Massive context window','Multimodal native','Google integration','Strong reasoning'],ARRAY['Inconsistent creative output','Privacy concerns','Less personality'],ARRAY['AI chat','multimodal','Google','reasoning'],'{"es":{"tagline":"El asistente AI multimodal más capaz de Google.","description":"Gemini es el modelo AI insignia de Google, profundamente integrado con Google Workspace. Gemini 1.5 Pro maneja ventanas de contexto de 1M de tokens, ideal para bases de código extensas.","useCases":["Análisis de documentos","Generación de código","Comprensión de imágenes","Tareas de contexto largo","Google Workspace"],"pros":["Ventana de contexto enorme","Multimodal nativo","Integración con Google","Razonamiento sólido"],"cons":["Salida creativa inconsistente","Preocupaciones de privacidad","Menos personalidad"],"editorial":"El rey de la ventana de contexto. Cuando necesitas analizar una base de código entera de un solo vistazo, Gemini no tiene rival."},"it":{"tagline":"L''assistente AI multimodale più capace di Google.","description":"Gemini è il modello AI di punta di Google, integrato in profondità con Google Workspace. Gemini 1.5 Pro gestisce finestre di contesto da 1M di token, ideale per codebase estese.","useCases":["Analisi documenti","Generazione codice","Comprensione immagini","Task con contesto lungo","Google Workspace"],"pros":["Finestra di contesto enorme","Multimodale nativo","Integrazione Google","Ragionamento solido"],"cons":["Output creativo inconsistente","Preoccupazioni privacy","Meno personalità"],"editorial":"Il re della finestra di contesto. Quando hai bisogno di analizzare un''intera codebase in un solo colpo, Gemini non ha rivali."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (26,'hubspot-ai','HubSpot AI','Sales','Freemium',false,'https://hubspot.com','2025-05-08','AI-powered CRM that writes scores and closes for you.','HubSpot AI embeds generative AI across its entire CRM platform from writing cold emails and scoring leads to forecasting pipeline and summarizing calls.','m','⊕','The most complete AI sales suite for teams that want everything in one place.',ARRAY['Lead scoring','Email personalization','Pipeline forecasting','Call summaries','CRM automation'],ARRAY['All-in-one platform','Generous free tier','Strong integrations','Easy onboarding'],ARRAY['Gets expensive at scale','AI needs data','Opinionated workflow'],ARRAY['CRM','sales','automation','lead generation'],'{"es":{"tagline":"CRM con IA que escribe, puntúa y cierra por ti.","description":"HubSpot AI integra la IA generativa en toda su plataforma CRM, desde la escritura de emails fríos y la puntuación de leads hasta la previsión del pipeline y el resumen de llamadas.","useCases":["Puntuación de leads","Personalización de emails","Previsión del pipeline","Resúmenes de llamadas","Automatización CRM"],"pros":["Plataforma todo en uno","Plan gratuito generoso","Integraciones sólidas","Onboarding sencillo"],"cons":["Se encarece a escala","La IA necesita datos","Flujo de trabajo opinado"],"editorial":"La suite de ventas con IA más completa para equipos que quieren todo en un solo lugar."},"it":{"tagline":"CRM con AI che scrive, punteggia e chiude per te.","description":"HubSpot AI integra l''AI generativa in tutta la sua piattaforma CRM, dalla scrittura di cold email e il punteggio dei lead alla previsione del pipeline e il riepilogo delle chiamate.","useCases":["Scoring dei lead","Personalizzazione email","Previsione pipeline","Riepiloghi chiamate","Automazione CRM"],"pros":["Piattaforma all-in-one","Piano gratuito generoso","Integrazioni solide","Onboarding semplice"],"cons":["Diventa costoso a scala","L''AI ha bisogno di dati","Workflow vincolato"],"editorial":"La suite di vendita AI più completa per i team che vogliono tutto in un unico posto."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (27,'apollo','Apollo.io','Sales','Freemium',false,'https://apollo.io','2025-05-06','AI prospecting that finds enriches and sequences leads.','Apollo combines a 275M contact database with AI sequencing and enrichment. Signal-based lead scoring helps reps focus on accounts most likely to convert.','m','◉','The prospecting engine sales teams actually use. 275M contacts plus AI sequencing.',ARRAY['Lead prospecting','Email sequencing','Contact enrichment','Intent data','Sales analytics'],ARRAY['Massive contact database','Strong enrichment','Signal scoring','Affordable entry'],ARRAY['Data accuracy varies','UI complex','Deliverability care needed'],ARRAY['prospecting','sales','outreach','lead generation'],'{"es":{"tagline":"Prospección con IA que encuentra, enriquece y secuencia leads.","description":"Apollo combina una base de datos de 275M de contactos con secuenciación y enriquecimiento con IA. La puntuación de leads basada en señales ayuda a los equipos a centrarse en las cuentas más propensas a convertir.","useCases":["Prospección de leads","Secuenciación de emails","Enriquecimiento de contactos","Datos de intención","Análisis de ventas"],"pros":["Enorme base de datos de contactos","Enriquecimiento sólido","Puntuación por señales","Precio de entrada asequible"],"cons":["La precisión de datos varía","UI compleja","Hay que cuidar la entregabilidad"],"editorial":"El motor de prospección que los equipos de ventas realmente usan. 275M de contactos más secuenciación con IA."},"it":{"tagline":"Prospecting AI che trova, arricchisce e sequenzia i lead.","description":"Apollo combina un database di 275M di contatti con sequenziamento e arricchimento AI. Il lead scoring basato sui segnali aiuta i team a concentrarsi sugli account più propensi a convertire.","useCases":["Prospecting lead","Sequenziamento email","Arricchimento contatti","Dati di intento","Analytics vendite"],"pros":["Enorme database contatti","Arricchimento solido","Scoring per segnali","Ingresso accessibile"],"cons":["La precisione dei dati varia","UI complessa","Attenzione alla deliverability"],"editorial":"Il motore di prospecting che i team di vendita usano davvero. 275M di contatti più sequenziamento AI."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (29,'n8n','n8n','Automation','Freemium',false,'https://n8n.io','2025-05-02','Open-source workflow automation you can self-host.','n8n is the open-source alternative to Zapier and Make offering full control over automation infrastructure. Self-host for complete data sovereignty. 400+ native integrations.','m','∞','The automation tool for teams that refuse to give their data to third parties.',ARRAY['Self-hosted automation','Custom integrations','Data pipelines','Developer workflows','AI agents'],ARRAY['Open source','Self-hostable','Custom code nodes','AI agent support'],ARRAY['Technical setup','Smaller community','Less polished UI'],ARRAY['automation','open-source','self-hosted','developer'],'{"es":{"tagline":"Automatización open-source que puedes autoalojar.","description":"n8n es la alternativa open-source a Zapier y Make que ofrece control total sobre la infraestructura de automatización. Alójalo tú mismo para soberanía total de tus datos. 400+ integraciones nativas.","useCases":["Automatización self-hosted","Integraciones personalizadas","Pipelines de datos","Flujos de trabajo para desarrolladores","Agentes de IA"],"pros":["Open source","Autoalojable","Nodos de código personalizado","Soporte para agentes de IA"],"cons":["Configuración técnica","Comunidad más pequeña","UI menos pulida"],"editorial":"La herramienta de automatización para equipos que no quieren dar sus datos a terceros."},"it":{"tagline":"Automazione workflow open-source self-hostabile.","description":"n8n è l''alternativa open-source a Zapier e Make che offre controllo totale sull''infrastruttura di automazione. Self-hostabile per la completa sovranità sui dati. 400+ integrazioni native.","useCases":["Automazione self-hosted","Integrazioni personalizzate","Pipeline dati","Workflow per sviluppatori","Agenti AI"],"pros":["Open source","Self-hostabile","Nodi di codice personalizzato","Supporto agenti AI"],"cons":["Configurazione tecnica","Comunità più piccola","UI meno rifinita"],"editorial":"Lo strumento di automazione per i team che non vogliono dare i propri dati a terzi."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (30,'elicit','Elicit','Research','Freemium',false,'https://elicit.com','2025-04-30','AI research assistant that reads papers for you.','Elicit automates literature review by searching and summarizing academic papers. Get a structured table of relevant studies with key findings extracted.','s','◑','The fastest way to get up to speed on any academic topic. Signal without noise.',ARRAY['Literature review','Academic research','Evidence synthesis','Systematic reviews','Research summaries'],ARRAY['Academic specialized','Structured data extraction','Saves days of work','Citation tracking'],ARRAY['Academic papers only','Pro for large reviews','Not general research'],ARRAY['research','academic','papers','literature review'],'{"es":{"tagline":"Asistente de investigación que lee papers por ti.","description":"Elicit automatiza las revisiones bibliográficas buscando y resumiendo artículos académicos. Obtén una tabla estructurada de estudios relevantes con los hallazgos clave extraídos.","useCases":["Revisión bibliográfica","Investigación académica","Síntesis de evidencia","Revisiones sistemáticas","Resúmenes de investigación"],"pros":["Especializado en académico","Extracción de datos estructurada","Ahorra días de trabajo","Seguimiento de citas"],"cons":["Solo artículos académicos","Pro para revisiones grandes","No para investigación general"],"editorial":"La forma más rápida de ponerse al día en cualquier tema académico. Señal sin ruido."},"it":{"tagline":"Assistente di ricerca che legge i paper al posto tuo.","description":"Elicit automatizza le revisioni della letteratura cercando e riassumendo articoli accademici. Ottieni una tabella strutturata di studi rilevanti con i risultati chiave estratti.","useCases":["Revisione letteratura","Ricerca accademica","Sintesi delle evidenze","Revisioni sistematiche","Riepiloghi di ricerca"],"pros":["Specializzato in accademico","Estrazione dati strutturata","Risparmia giorni di lavoro","Tracciamento citazioni"],"cons":["Solo articoli accademici","Pro per grandi revisioni","Non per ricerca generale"],"editorial":"Il modo più rapido per aggiornarsi su qualsiasi argomento accademico. Segnale senza rumore."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (35,'loom','Loom','Productivity','Freemium',false,'https://loom.com','2025-04-14','AI-enhanced async video messaging for teams.','Loom lets you record and share video messages instantly. AI auto-generates titles summaries and action items from recordings and removes filler words.','s','⊙','The tool that replaced a thousand unnecessary meetings. Two minutes beats thirty.',ARRAY['Async team updates','Design feedback','Bug reports','Customer demos','Onboarding'],ARRAY['Instant sharing','AI summaries','Filler removal','Comment on moments'],ARRAY['Storage limits','Video quality caps','Not for long-form'],ARRAY['video','productivity','async','communication'],'{"es":{"tagline":"Mensajería de vídeo asíncrona con IA para equipos.","description":"Loom te permite grabar y compartir mensajes de vídeo al instante. La IA genera automáticamente títulos, resúmenes y puntos de acción de las grabaciones, y elimina las muletillas.","useCases":["Actualizaciones asíncronas del equipo","Feedback de diseño","Informes de errores","Demos para clientes","Onboarding"],"pros":["Compartir al instante","Resúmenes con IA","Eliminación de muletillas","Comentar en momentos concretos"],"cons":["Límites de almacenamiento","Topes en calidad de vídeo","No para contenido largo"],"editorial":"La herramienta que reemplazó mil reuniones innecesarias. Dos minutos ganan a treinta."},"it":{"tagline":"Messaggistica video asincrona con AI per i team.","description":"Loom ti consente di registrare e condividere messaggi video all''istante. L''AI genera automaticamente titoli, riepiloghi e punti d''azione dalle registrazioni, e rimuove le parole di riempimento.","useCases":["Aggiornamenti asincroni del team","Feedback di design","Segnalazioni bug","Demo per clienti","Onboarding"],"pros":["Condivisione istantanea","Riepiloghi AI","Rimozione filler","Commenti su momenti precisi"],"cons":["Limiti di storage","Tetti sulla qualità video","Non per contenuto lungo"],"editorial":"Lo strumento che ha sostituito mille riunioni inutili. Due minuti battono trenta."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (37,'synthesia','Synthesia','Video','Paid',false,'https://synthesia.io','2025-04-08','Create professional AI videos with digital avatars.','Synthesia generates professional videos from text using AI avatars and voices in 140+ languages. Used by L&D teams to create training videos without cameras.','s','▣','Enterprise standard for video at scale. 50 training videos in 10 languages without a film crew.',ARRAY['Training videos','Product demos','Internal comms','Multilingual content','E-learning'],ARRAY['No camera needed','140+ languages','Professional avatars','Fast production'],ARRAY['Avatar quality varies','Expensive for small teams','Less authentic'],ARRAY['video','avatar','AI presenter','e-learning'],'{"es":{"tagline":"Crea vídeos profesionales con avatares de IA.","description":"Synthesia genera vídeos profesionales a partir de texto usando avatares y voces de IA en más de 140 idiomas. Usada por equipos de LD para crear vídeos de formación sin cámaras.","useCases":["Vídeos de formación","Demos de producto","Comunicaciones internas","Contenido multilingüe","E-learning"],"pros":["Sin cámara necesaria","140+ idiomas","Avatares profesionales","Producción rápida"],"cons":["La calidad del avatar varía","Caro para equipos pequeños","Menos auténtico"],"editorial":"El estándar empresarial para vídeo a escala. 50 vídeos de formación en 10 idiomas sin equipo de rodaje."},"it":{"tagline":"Crea video professionali con avatar AI.","description":"Synthesia genera video professionali da testo usando avatar AI e voci in 140+ lingue. Usata dai team LD per creare video formativi senza telecamere.","useCases":["Video formativi","Demo di prodotto","Comunicazioni interne","Contenuto multilingue","E-learning"],"pros":["Nessuna telecamera necessaria","140+ lingue","Avatar professionali","Produzione rapida"],"cons":["La qualità degli avatar varia","Costoso per team piccoli","Meno autentico"],"editorial":"Lo standard enterprise per il video su larga scala. 50 video formativi in 10 lingue senza troupe cinematografica."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (39,'semrush-ai','Semrush AI','Marketing','Paid',false,'https://semrush.com','2025-04-03','SEO and content intelligence powered by AI.','Semrush integrates AI across its SEO platform from keyword research to ContentShake AI writer that generates SEO-optimized articles.','s','◎','The SEO platform marketing teams trust most now with AI in every workflow.',ARRAY['SEO research','Content briefs','Keyword analysis','Competitor research','Content optimization'],ARRAY['All-in-one SEO','AI content integrated','Deep competitor data','Agency trusted'],ARRAY['Expensive','Overwhelming for beginners','AI features are add-ons'],ARRAY['SEO','marketing','content','keyword research'],'{"es":{"tagline":"Inteligencia SEO y de contenido con IA.","description":"Semrush integra la IA en toda su plataforma SEO, desde la investigación de palabras clave hasta el redactor ContentShake AI que genera artículos optimizados para SEO.","useCases":["Investigación SEO","Briefings de contenido","Análisis de palabras clave","Investigación de competidores","Optimización de contenido"],"pros":["SEO todo en uno","IA integrada en el contenido","Datos profundos de competidores","De confianza para agencias"],"cons":["Caro","Abrumador para principiantes","Las funciones de IA son complementos"],"editorial":"La plataforma SEO en la que más confían los equipos de marketing, ahora con IA en cada flujo de trabajo."},"it":{"tagline":"Intelligenza SEO e contenuto potenziata dall''AI.","description":"Semrush integra l''AI in tutta la sua piattaforma SEO, dalla ricerca di parole chiave al redattore ContentShake AI che genera articoli ottimizzati per la SEO.","useCases":["Ricerca SEO","Brief per contenuti","Analisi parole chiave","Ricerca competitor","Ottimizzazione contenuti"],"pros":["SEO all-in-one","AI integrata nel contenuto","Dati approfonditi sui competitor","Affidato dalle agenzie"],"cons":["Costoso","Travolgente per i principianti","Le funzionalità AI sono componenti aggiuntivi"],"editorial":"La piattaforma SEO di cui i team marketing si fidano di più, ora con AI in ogni flusso di lavoro."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tools (id,slug,name,category,pricing,featured,website,added_at,tagline,description,tier,logo,editorial,use_cases,pros,cons,tags,i18n)
VALUES (40,'replit-ai','Replit AI','Coding','Freemium',false,'https://replit.com','2025-04-01','Code build and deploy apps in the browser.','Replit is a browser-based coding environment with AI in every layer. Ghostwriter completes code explains errors and generates projects from natural language.','s','⬡','The fastest path from idea to deployed app. Removes every barrier between idea and running code.',ARRAY['Prototyping','Learning to code','Collaborative coding','App deployment','Script automation'],ARRAY['No setup required','AI plus IDE plus hosting','Great for beginners','Real-time collaboration'],ARRAY['Performance limits','Not for production scale','Vendor lock-in risk'],ARRAY['coding','browser IDE','prototyping','deployment'],'{"es":{"tagline":"Codifica, construye y despliega apps en el navegador.","description":"Replit es un entorno de codificación en el navegador con IA en cada capa. Ghostwriter completa el código, explica los errores y genera proyectos a partir del lenguaje natural.","useCases":["Prototipado","Aprender a programar","Codificación colaborativa","Despliegue de aplicaciones","Automatización de scripts"],"pros":["Sin configuración necesaria","IA + IDE + hosting","Ideal para principiantes","Colaboración en tiempo real"],"cons":["Límites de rendimiento","No apto para producción a escala","Riesgo de dependencia del proveedor"],"editorial":"El camino más rápido de la idea a la app desplegada. Elimina cada barrera entre la idea y el código en ejecución."},"it":{"tagline":"Codifica, costruisci e deploya app nel browser.","description":"Replit è un ambiente di codifica nel browser con AI in ogni livello. Ghostwriter completa il codice, spiega gli errori e genera progetti dal linguaggio naturale.","useCases":["Prototipazione","Imparare a programmare","Codifica collaborativa","Deploy di app","Automazione script"],"pros":["Nessuna configurazione","AI + IDE + hosting","Ottimo per principianti","Collaborazione in tempo reale"],"cons":["Limiti di prestazioni","Non per produzione su larga scala","Rischio di lock-in del vendor"],"editorial":"Il percorso più rapido dall''idea all''app deployata. Rimuove ogni barriera tra l''idea e il codice in esecuzione."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

